run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goimports
    - gofmt
    - whitespace
    - nilerr
    - prealloc
    - exportloopref
  disable:
    - gocyclo
    - funlen
    - gocognit

issues:
  exclude-dirs:
    - vendor
    - bin
